# Generated by Django 4.0.4 on 2022-05-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_rename_numberofbooks_book_number_of_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.CharField(max_length=10),
        ),
    ]
